language: php

sudo: false

branches:
  only:
  - master
  - 6.0.x

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.3
      env: SYMFONY_VERSION=4.0.*

env:
    global:
        - LANG=en_US.UTF-8
install:
  - travis_retry composer require --no-interaction --prefer-source symfony/process:${SYMFONY_VERSION} symfony/filesystem:${SYMFONY_VERSION}

before_script:
  - phpenv config-rm xdebug.ini

script:
  - ./vendor/bin/phpunit
